config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :airports, :flights
  resources :bookings, :passengers

  root 'flights#index'
  get '/test_email', to: 'passengers#test_email'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  belongs_to :passenger
  accepts_nested_attributes_for :passenger

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: "Airport", foreign_key: "from_airport_id"
  belongs_to :to_airport, class_name: "Airport", foreign_key: "to_airport_id"
  
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end


  def new
    # new is for new instance of specific model
    # build is for creating a new instance withing an AR association (apparently)
    @booking = Booking.new
  end
  def create
    puts "CREATING"
    p params
    p booking_params
    p booking_params[:passenger]

    @passenger = Passenger.create(passenger_params)
    @booking = Booking.new(flight_id: booking_params[:flight_id],
                           passenger_id: @passenger.id)
    @flight = Flight.find(@booking.flight_id)

    if @booking.save
      puts "SAVED"
      PassengerMailer.with(passenger: @passenger, flight: @flight).welcome_email.deliver_later
      redirect_to root_url
      # redirect etc
    else
      puts "NOT SAVED"
      flash[:warning] = "somethings wrong"
      redirect_to root_url
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id)
  end
  def passenger_params
    params.require(:passenger).permit(:name, :email)
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: %i[show edit update destroy]
  def index
    @flights = Flight.where(from_airport_id: params[:from_airport],
                           to_airport_id: params[:to_airport],
                           start: params[:start])
    @all_flights = Flight.all
    @flight = Flight.new
    # surely a better way to do this next line with query
    #@dates  = Flight.all.each_with_object([]) { |flight, memo| memo << flight.start }
  end

  def new
  end
  def create
  end
  def show
  end


  private
  def set_flight
    @flight = Flight.find(params[:id])
  end


  
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  def create
    @passenger = Passenger.create!(passenger_params)
    if @passenger.save
      # redirect etc
    else
    end
  end
  def test_email
      #PassengerMailer.test_email.deliver_later
      PassengerMailer.test_email.deliver_now
      redirect_to root_url
  end

  private
  def passenger_params
    params.require(:passenger).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_booking.html.erb
<h4>Booking:</h4>
<%= render partial: "flights/flight", locals: {flight: booking.flight} %>

<%= render partial: "passengers/passenger", locals: {passenger: booking.passenger} %>

app/views/bookings/index.html.erb
<%= render @bookings %>

app/views/bookings/new.html.erb
<h3>Booking for:</h3>
<%# render "flights/flight", locals: {flight: Flight.find(params[:flight])} %>
<br>
<%= form_with model: @booking do |bform| %>
  <%= bform.hidden_field :flight_id, value: params[:flight] %>



  <%= fields_for :passenger do |pform| %>
    <%# pform.hidden_field :passenger_id, value: nil %>
    <%= pform.label :name, "Name: " %>
    <%= pform.text_field :name %>
    <%= pform.label :email, "Email: " %>
    <%= pform.text_field :email %>
  <% end %>
  <%= bform.submit "Create booking" %>

<% end %>

app/views/flights/_flight.html.erb
<%= link_to(flight_path(flight), class: "flight") do %>
  <%= content_tag(:div, "From: #{flight.from_airport.code} (#{flight.from_airport.name})") %>
  <%= content_tag(:div, "To: #{flight.to_airport.code} (#{flight.to_airport.name})") %>
  <%= content_tag(:div, "Start: #{flight.start}") %>
  <%= content_tag(:div, "Duration: #{flight.duration}") %>
<% end %>

app/views/flights/index.html.erb
<h1>Flights!</h1>
<%= link_to "Test email", test_email_path %>
<%= form_with(url: flights_path, method: :get, class: "flight_select") do |form| %>
  <%= content_tag(:div, "From:") %>
  <%= content_tag(:div, "To:") %>
  <%= content_tag(:div, "Date:") %>

  <%= form.collection_select :from_airport, Airport.all, :id, :code %>
  <%= form.collection_select :to_airport, Airport.all, :id, :code %>
  <%= form.collection_select :start, @all_flights, :start, :start %>
  <%= form.submit "Show flights" %>
<% end %>

<% if @flights %>
  <h3>Matching flights:</h3>
  <%= render @flights %>
  <% if @flights.empty? %>
    <p>(none)</p>
  <% end %>
<% end %>


<h3>All flights</h3>
<%= render @all_flights %>

app/views/flights/show.html.erb
<h1>This flight!</h1>
<%= render @flight %>
<%= link_to "make a booking for this flight", new_booking_path(params: {flight: @flight.id}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <aside class="params">
      <%= params.inspect %>
    </aside>
    <%= yield %>
  </body>
</html>

app/views/passengers/_passenger.html.erb
<h4>Passenger</h4>
<%= content_tag(:div, "Name: #{passenger.name}") %>
<%= content_tag(:div, "Email: #{passenger.email}") %>